// <auto-generated />
using System;
using Adoptapal.Business.Definitions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Adoptapal.Business.Definitions.Migrations
{
    [DbContext(typeof(AdoptapalDbContext))]
    [Migration("20230826102219_testData")]
    partial class testData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Adoptapal.Business.Definitions.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Lat")
                        .HasColumnType("float");

                    b.Property<double?>("Long")
                        .HasColumnType("float");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44674b8f-3fdb-46a4-840e-5415feb68b1d"),
                            City = "Sample City",
                            Lat = 37.774900000000002,
                            Long = -122.4194,
                            Street = "Main St",
                            StreetNumber = "1",
                            Zip = "12345"
                        });
                });

            modelBuilder.Entity("Adoptapal.Business.Definitions.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnimalCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsMale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tiere", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0500293e-bb8a-4c1d-b1a8-2edddf992f3c"),
                            AnimalCategory = "Dog",
                            Birthday = new DateTime(2019, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "White",
                            Description = "A cute and friendly dog",
                            ImageFilePath = "path/to/animal1.jpg",
                            IsMale = true,
                            Name = "Fluffy",
                            Weight = 15.5f
                        },
                        new
                        {
                            Id = new Guid("e0597683-c3f2-41e8-95e6-19f052c2bb83"),
                            AnimalCategory = "Cat",
                            Birthday = new DateTime(2020, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "Gray",
                            Description = "A playful and curious cat",
                            ImageFilePath = "path/to/animal2.jpg",
                            IsMale = false,
                            Name = "Whiskers",
                            Weight = 8.2f
                        });
                });

            modelBuilder.Entity("Adoptapal.Business.Definitions.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PostTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Kommentare", (string)null);
                });

            modelBuilder.Entity("Adoptapal.Business.Definitions.FavoritAnimals", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnimalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("UserId");

                    b.ToTable("Lieblingstiere", (string)null);
                });

            modelBuilder.Entity("Adoptapal.Business.Definitions.MessageBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PostTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("Adoptapal.Business.Definitions.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Nutzer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("844bb58e-a70f-4345-ad95-f08e82cdb2ee"),
                            Email = "john@example.com",
                            Name = "John Doe",
                            Password = "54DE7F606F2523CBA8EFAC173FAB42FB7F59D56CEFF974C8FDB7342CF2CFE345",
                            PhoneNumber = "+1234567890"
                        },
                        new
                        {
                            Id = new Guid("89ca65f5-787f-4b92-ab9e-2c86f6d426a9"),
                            Email = "jane@example.com",
                            Name = "Jane Smith",
                            Password = "54DE7F606F2523CBA8EFAC173FAB42FB7F59D56CEFF974C8FDB7342CF2CFE345",
                            PhoneNumber = "+9876543210"
                        });
                });

            modelBuilder.Entity("Adoptapal.Business.Definitions.Animal", b =>
                {
                    b.HasOne("Adoptapal.Business.Definitions.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adoptapal.Business.Definitions.Comment", b =>
                {
                    b.HasOne("Adoptapal.Business.Definitions.MessageBoard", "Post")
                        .WithMany()
                        .HasForeignKey("PostId");

                    b.HasOne("Adoptapal.Business.Definitions.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adoptapal.Business.Definitions.FavoritAnimals", b =>
                {
                    b.HasOne("Adoptapal.Business.Definitions.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId");

                    b.HasOne("Adoptapal.Business.Definitions.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Animal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adoptapal.Business.Definitions.MessageBoard", b =>
                {
                    b.HasOne("Adoptapal.Business.Definitions.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adoptapal.Business.Definitions.User", b =>
                {
                    b.HasOne("Adoptapal.Business.Definitions.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
